name: RPW
favicon: null
layout_spectrum: 0.22531085996888578
typography_spectrum: 0.9530843165703118
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.679469597293064
  lightness: 0.013068027328699827
  saturation: 0.8626714474521577
  rhythmicContrast: 0.5889647426083684
purpose: []
