name: RPW
favicon: null
layout_spectrum: 0.22531085996888578
typography_spectrum: 0.79389
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#11100e'
    - '#f4e8d4'
    - '#41352b'
    - '#8694b6'
    - '#5d7382'
  brandStrength: 0.679469597293064
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
